### ISSUE TITLE
Test from README fails

### ISSUE THREAD

**Issue by bhawandeepsingh** [google/vizier#1018]
Hi,
I am using Python 3.10.12 in Ubuntu 22.04.
I pip installed the default jax version (also tried with all).
I run the test code given in the README -

```
from vizier.service import clients
from vizier.service import pyvizier as vz

# Objective function to maximize.
def evaluate(w: float, x: int, y: float, z: str) -> float:
  return w**2 - y**2 + x * ord(z)

# Algorithm, search space, and metrics.
study_config = vz.StudyConfig(algorithm='GAUSSIAN_PROCESS_BANDIT')
study_config.search_space.root.add_float_param('w', 0.0, 5.0)
study_config.search_space.root.add_int_param('x', -2, 2)
study_config.search_space.root.add_discrete_param('y', [0.3, 7.2])
study_config.search_space.root.add_categorical_param('z', ['a', 'g', 'k'])
study_config.metric_information.append(vz.MetricInformation('metric_name', goal=vz.ObjectiveMetricGoal.MAXIMIZE))

# Setup client and begin optimization. Vizier Service will be implicitly created.
study = clients.Study.from_study_config(study_config, owner='my_name', study_id='example')
for i in range(10):
  suggestions = study.suggest(count=1)
  for suggestion in suggestions:
    params = suggestion.parameters
    objective = evaluate(params['w'], params['x'], params['y'], params['z'])
    suggestion.complete(vz.Measurement({'metric_name': objective}))
```

I get the below error - 
```
/vizier/vizier/_src/service/stubs_util.py", line 24, in <module>
    from vizier._src.service import pythia_service_pb2_grpc
ImportError: cannot import name 'pythia_service_pb2_grpc' from 'vizier._src.service' (unknown location)
```
Is there any PATH requirement that I missed ? I tried checking but could not find anything.
Can you please help ?
Thanks

**Comment by sagipe** [comment]
Hi,
Can you check to see if you see proto and `pythia_service_pb2_grpc.py` files under `vizier/_src/service`?

During `pip install`, it should run `bash build_protos.sh` (https://github.com/google/vizier/blob/main/build_protos.sh) which should download the proto files and build the `grpc` Python libs under `vizier/_src/service`
(this is done in https://github.com/google/vizier/blob/main/setup.py#L65).

If you don't see them, can you try manually running `bash build_protos.sh` from the root folder of the `vizier` directory?

Best,
Sagi

**Comment by bhawandeepsingh** [comment]
Hi Sagi,
Thanks a lot, I did not have the mentioned files, run the script and the error is resolved.
Thanks and best regards
Bhawandeep Singh

**Comment by GTMalogic** [comment]
Hi Sagi, I also have the same fail as Bhawandeep Singh.
I  ran bash build_protos.sh from the root folder of the vizier directory, but pythia_service_pb2_grpc still cannot be found. How can I fix it?
The following part is what I get after build_protos.sh.
+++ dirname build_protos.sh
++ realpath .
+ THIS_DIR=/f/桌面/学术/毕业相关/各单位/华为/神经网络与大模型超参调优/vizier
+ DEPOT=/f/桌面/学术/毕业相关/各单位/华为/神经网络与大模型超参调优/vizier/../../../..
+ cd /f/桌面/学术/毕业相关/各单位/华为/神经网络与大模型超参调优/vizier
++ mktemp -d
+ TMPDIR=/tmp/tmp.uaDQBNHCn9
+ cd /tmp/tmp.uaDQBNHCn9
+ python -m wget https://github.com/googleapis/googleapis/archive/master.tar.gz
100% [..........................................................................] 8845604 / 8845604
Saved under googleapis-master.tar.gz
+ tar xzf googleapis-master.tar.gz
+ cp -r googleapis-master/google /f/桌面/学术/毕业相关/各单位/华为/神经网络与大模型超参调优/vizier/vizier/_src/service/
+ rm -rf /tmp/tmp.uaDQBNHCn9
+ for proto_name in *.proto
+ python3 -m grpc_tools.protoc --python_out=vizier/_src/service --grpc_python_out=vizier/_src/service --proto_path=vizier/_src/service --experimental_allow_proto3_optional vizier/_src/service/key_value.proto vizier/_src/service/pythia_service.proto vizier/_src/service/study.proto vizier/_src/service/vizier_oss.proto vizier/_src/service/vizier_service.proto

**Comment by xingyousong** [comment]
Hi @GTMalogic, we suspect that the protobuf compiler fails on non-English directories (e.g. Chinese). Can you try installing the package on a purely English folder?

**Comment by GTMalogic** [comment]
> Hi @GTMalogic, we suspect that the protobuf compiler fails on non-English directories (e.g. Chinese). Can you try installing the package on a purely English folder?
I re-install the package in a purely English path, but pythia_service_pb2_grpc still cannot be found. Do I need to install google-vizier[all]? But when I try to pip install google-vizier[all] instead of [jax], it fails with "ImportError: cannot import name 'appdirs' from 'pkg_resources.extern'"

**Comment by GTMalogic** [comment]
I checked build_protos.sh. It seems that we have to do (python3 -m grpc_tools.protoc) for all files in the folder ending with .proto？But there is no file named pythia_service_pb2_grpc.proto in my folder at all. Is this the reason I cannot get pythia_service_pb2_grpc.py? Is there something wrong?

**Comment by xingyousong** [comment]
@GTMalogic are you installing from pip, i.e. `pip install google-vizier[jax]`? 
Strongly do *not* recommend manually installing the package on your own.
